### PR TITLE
Fixes for Deviantart Ripper

### LINKED ISSUE #1303: DeviantArt ripper does not download entire gallery
* Ripme version: 1.7.83
* Java version: 1.8.0_201
* Operating system: 6.1.7601
* Exact URL you were trying to rip when the problem occurred: https://www.deviantart.com/heavenhellexe/gallery/?catpath=/ (Warning: NSFW)
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

The full gallery of the user gets ripped.

## Actual Behavior
Image 125
Image 126

### PR DESCRIPTION
**Pull request by MrPlaygon**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [X] a bug fix (Fix #1303)
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix
* [ ] a new feature

# Description

Please add details about your change here.

Fixes for https://github.com/RipMeApp/ripme/issues/1303

Gallery/Favourites URL without trailing / works now.
Added some failsaves to prevent 404's with the image galleries mentioned in the issue above.
Changed the login. It actually works now.
Added some documentation

Tested with URLS mentioned in Javadoc.

# Testing

Required verification:
* [ ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [ ] I've verified that this change works as intended.
  * [X] Downloads all relevant content.
  * [X] Downloads content from multiple pages (as necessary or appropriate).
  * [X] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [ ] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

File: src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java [hunk 1]
```diff
@@ -344,7 +354,7 @@ public String getGID(URL url) throws MalformedURLException {
 		Matcher artistM = artistP.matcher(s);
 		if (s.endsWith("?catpath=/")) {
 			albumname = "all";
-		} else if (s.endsWith("/favourites/") || s.endsWith("/gallery/")) {
+		} else if (s.endsWith("/favourites/") || s.endsWith("/gallery/") || s.endsWith("/gallery") || s.endsWith("/favourites")) { //added andings without trailing / because of https://github.com/RipMeApp/ripme/issues/1303
```
Comment (rautamiekka) [inline src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java]: Shouldn't you just have the ones without a trailing slash since you'll match anyway ?

Comment (MrPlaygon) [reply src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java]: I don't think so if I understand you correctly.
Deviantart redirects e.g. https://www.deviantart.com/apofiss/gallery to https://www.deviantart.com/apofiss/gallery/

so in a normal use case you would never have something similiar to the first URL. I just added theses because of the issue mentioned [here](https://github.com/RipMeApp/ripme/issues/1303). 
It might be a good idea to look into Regex again to replace them and make it look cleaner. 🤔
