### PR TITLE
Insagram ripper now can get all pages of a profile

### LINKED ISSUE #474: Instagram Ripper only getting first page
@cyian-1756 
* Ripme version: 1.7.25
* Java version: Version 8 Build 161
* Operating system: Win 7 64bit
* Exact URL you were trying to rip when the problem occurred:
https://instagram.com/taylorswift  This is a URL I tested it with, but it does it with ALL Instagram URL's 
* Please include any additional information about how to reproduce the problem:
When I start the rip it downloads the first 12 pictures then starts saying "Downloading Next Page"  but there is nothing other than that showing.  
## Expected Behavior
To download all the pictures
Detail the expected behavior here.

## Actual Behavior
[Bug.txt](https://github.com/RipMeApp/ripme/files/1813835/Bug.txt)
That is what it is doing, I've tried several different instagram sites.
Detail the actual (incorrect) behavior here. You can post log snippets or attach log files to your issue report.

### PR DESCRIPTION
**Pull request by cyian-1756**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [X] a bug fix (Fix #474)

# Description

I added support for instagrams new JSON structure and changed to the new api endpoint for getting the next page

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

File: src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java [hunk 1]
```diff
@@ -136,7 +140,21 @@ public String getGID(URL url) throws MalformedURLException {
...
+                " <head></head>\n" +
+                " <body>", "");
+        t.replaceAll("</body>\n" +
+                "</html>", "");
+        return t;
+    }
+
+
     private JSONObject getJSONFromPage(Document firstPage) throws IOException {
+        // Check if this page is HTML + JSON or jsut json
```
Comment (rautamiekka) [inline src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java]: Typo: jsut
