### PR TITLE
JabArchivesRipper now allows for www. to appear in url

### LINKED ISSUE #853: Error attempting to rip any gallery on jabarchives.com
* Ripme version: 1.7.60
* Java version:  Version 8 Update 181
* Operating system:  Version 1803 (OS Build 17134.165)

* Exact URL you were trying to rip when the problem occurred: https://www.jabarchives.com/main/view/mew_Toons
* Please include any additional information about how to reproduce the problem:
Ripme recognizes the URL as being valid, providing the green text, however when pressing "Rip" the below behavior occurs.

## Expected Behavior
Sucessful rip, initiated with the rip button is pressed.

## Actual Behavior
(It appears that the ripper is always expecting "albumname" to be present, when that actually changes depending on which album is being viewed)

2018-08-03 16:28:09,460 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.JabArchivesRipper
2018-08-03 16:28:10,596 DEBUG ripper.AbstractRipper .getRipper() Found album ripper: com.rarchives.ripme.ripper.rippers.JabArchivesRipper
2018-08-03 16:28:10,596 ERROR ui.MainWindow .ripAlbum() Could not find ripper for URL https://www.jabarchives.com/main/view/mew_Toons
java.net.MalformedURLException: Expected javarchives.com URL format: jabarchives.com/main/view/albumname - got https://www.jabarchives.com/main/view/mew_Toons instead
	at com.rarchives.ripme.ripper.rippers.JabArchivesRipper.getGID(JabArchivesRipper.java:42)
	at com.rarchives.ripme.ripper.AbstractRipper.getAlbumTitle(AbstractRipper.java:475)
	at com.rarchives.ripme.ripper.AlbumRipper.setWorkingDir(AlbumRipper.java:192)
	at com.rarchives.ripme.ripper.AbstractRipper.setup(AbstractRipper.java:178)
	at com.rarchives.ripme.ui.MainWindow.ripAlbum(MainWindow.java:1128)
	at com.rarchives.ripme.ui.MainWindow.ripNextAlbum(MainWindow.java:1087)
	at com.rarchives.ripme.ui.MainWindow.access$600(MainWindow.java:67)
	at com.rarchives.ripme.ui.MainWindow$4.intervalAdded(MainWindow.java:852)
	at javax.swing.AbstractListModel.fireIntervalAdded(Unknown Source)
	at javax.swing.DefaultListModel.add(Unknown Source)
	at com.rarchives.ripme.ui.MainWindow$RipButtonHandler.actionPerformed(MainWindow.java:1162)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

### PR DESCRIPTION
**Pull request by cyian-1756**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [x] a bug fix (Fix #853)

# Description

Changed the getGID regex

# Testing

Required verification:
* [ ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [ ] I've verified that this change works as intended.
  * [ ] Downloads all relevant content.
  * [ ] Downloads content from multiple pages (as necessary or appropriate).
  * [ ] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [ ] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

File: src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java [hunk 1]
```diff
@@ -33,7 +33,7 @@ public String getDomain() {
 
     @Override
     public String getGID(URL url) throws MalformedURLException {
-        Pattern p = Pattern.compile("^https?://jabarchives.com/main/view/([a-zA-Z0-9_]+).*$");
+        Pattern p = Pattern.compile("^https?://(:?www.)jabarchives.com/main/view/([a-zA-Z0-9_]+).*$");
```
Comment (s104346) [inline src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java]: Shouldn't this be `(?:www\\.)?` instead of `(:?www.)`

Comment (cyian-1756) [reply src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java]: Yea it should

File: src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java [hunk 2]
```diff
@@ -33,7 +33,7 @@ public String getDomain() {
 
     @Override
     public String getGID(URL url) throws MalformedURLException {
-        Pattern p = Pattern.compile("^https?://(:?www.)jabarchives.com/main/view/([a-zA-Z0-9_]+).*$");
+        Pattern p = Pattern.compile("^https?://(:?www\\.)jabarchives.com/main/view/([a-zA-Z0-9_]+).*$");
```
Comment (s104346) [inline src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java]: You still haven't changed `:?` to `?:` to make it a non-capturing group
and it's still missing a `?` at the end to match both `http://www.jabarchives.com` and `http://jabarchives.com`
```
(:?www  .)       <- first attempt
(:?www\\.)       <- this commit
(?:www\\.)?      <- what I suggested
```

Comment (cyian-1756) [reply src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java]: > You still haven't changed :? to ?: to make it a non-capturing group

Thanks for catching that
