### PR TITLE
Fixed instagram ripper

### LINKED ISSUE #469: Instagram not working
* Ripme version: 1.7.24
* Java version:  8 update 151
* Operating system: Windows 7
* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/privatekanye
* Please include any additional information about how to reproduce the problem:

Instagram ripper isn't working at all for me for any instagram account. The ripper just gives me an error message: "JSONObject["TagPage"] not found." I've tried different versions of the ripper and still have the same issue. Anyone know what the issue could be and how to fix it?

### PR DESCRIPTION
**Pull request by cyian-1756**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [X] a bug fix (Fix #469)

# Description

I updated the ripper to work with IGs new JSON structure 

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by cyian-1756** [comment]
The failed test is for xhamster. It failed because the site is down

File: src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java [hunk 1]
```diff
@@ -212,23 +212,25 @@ private String getOriginalUrl(String imageURL) {
...
                 JSONObject data = (JSONObject) datas.get(i);
-                Long epoch = data.getLong("date");
+                data = data.getJSONObject("node");
+                Long epoch = data.getLong("taken_at_timestamp");
                 Instant instant = Instant.ofEpochSecond(epoch);
                 String image_date = DateTimeFormatter.ofPattern("yyyy_MM_dd_hh:mm_").format(ZonedDateTime.ofInstant(instant, ZoneOffset.UTC));
                 if (data.getString("__typename").equals("GraphSidecar")) {
                     try {
-                        Document slideShowDoc = Http.url(new URL ("https://www.instagram.com/p/" + data.getString("code"))).get();
+                        Document slideShowDoc = Http.url(new URL ("https://www.instagram.com/p/" + data.getString("shortcode"))).get();
```
Comment (rautamiekka) [inline src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java]: Consistency error: `new URL (` -> `new URL(`

Comment (cyian-1756) [reply src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java]: Fixed in my last push
